spring:
    h2:
        console:
            enabled: false
            path: /h2-console
    datasource:
         driver-class-name: org.h2.Driver
         url: jdbc:h2:mem:batchdb
         username: sa
         password:
    batch:
        jdbc:
            initialize-schema: embedded
        job:
            names: ${job.name:None}