server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    jdbc:
      initialize-schema: embedded
    job:
      names: ${job.name:NONE}
      enabled: true