server:
    port: 8000

spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        # driver-class-name: org.h2.Driver
        # url: jdbc:h2:mem:batchdb
        # username: sa
        # password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/logdb?serverTimezone=UTC&characterEncoding=UTF-8
        username: yung
        password: 1234
    batch:
        jdbc:
            initialize-schema: never
        job:
            names: ${job.name:None}